name: Build Website to APK

on:
  workflow_dispatch:
    inputs:
      website_url:
        description: 'Ссылка на ваш сайт (URL)'
        required: true
        default: 'https://perchance.org/urv-ai-chat'
      app_name:
        description: 'Название приложения'
        required: true
        default: 'URV AI Chat'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create static site configuration
        run: |
          mkdir -p build
          echo '<script>window.location.href="${{ github.event.inputs.website_url }}";</script>' > build/index.html

      - name: Convert to APK
        uses: darkshredder/web-to-app-action@main
        with:
          build-folder-path: "build"
          app-name: "${{ github.event.inputs.app_name }}"
          output-folder-path: "my-apks"

      - name: Upload Finished APK
        uses: actions/upload-artifact@v4
        with:
          name: Ready-APK-File
          path: my-apks/
          
