name: Build Website to APK

on:
  workflow_dispatch:
    inputs:
      website_url:
        description: 'https://perchance.org/urv-ai-chat'
        required: true
        default: 'https://example.com'
      app_name:
        description: 'URV AI'
        required: true
        default: 'My App'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup Java (OpenJDK 17)
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Install website-to-apk tool
        run: npm install -g website-to-apk

      - name: Build APK File
        run: website-to-apk --url "${{ github.event.inputs.website_url }}" --name "${{ github.event.inputs.app_name }}"

      - name: Upload Finished APK
        uses: actions/upload-artifact@v4
        with:
          name: Ready-APK-File
          path: ./*.apk
          
